### ISSUE TITLE
Unnecessarily environment-specific

### ISSUE THREAD

**Issue by Diggsey** [w3c-ccg/http-signatures-test-suite#25]
Tests are running by calling `exec()` with an option like:

```
echo -e 'Date: Wed, 15 Apr 2020 23:38:05 GMT

{"hello": "world"}' | cat <path> - | <generator> canonicalize --headers "date"
```

This seems unnecessarily environment-specific to achieve the fairly simple goal of writing some input to the process.

**Comment by aljones15** [comment]
this is actually something I am hoping to work on the next iteration. Node's existing `process.stdout.write` should be able to replace the reliance on `echo` and `cat` while also allowing us to better format the resulting http message / command line options.

**Comment by Diggsey** [comment]
I already partially fixed it locally so I'll just PR that.
